import { type Block, type Locale, flatten } from './document.ts';
import type { Article } from './content-service.ts';
export const escape = (value:unknown) => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const scriptJson = (value:unknown) => JSON.stringify(value).replace(/</g,'\\u003c');
export const pathFor = (locale:Locale,slug='') => `${locale==='vi'?'/vi':''}/blog/${slug}`;
export function shell(title:string,locale:Locale,content:string,head='',script='/assets/blog/reader.js') {
  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · ClarkCant</title><link rel="icon" href="/assets/img/favicon.svg"><link rel="stylesheet" href="/assets/css/tokens.css"><link rel="stylesheet" href="/assets/blog/blog.css">${head}</head><body><a class="skip" href="#main">${locale==='vi'?'Đến nội dung':'Skip to content'}</a><header class="site-header"><a class="wordmark" href="/"><span class="orb-mark" aria-hidden="true"></span>ClarkCant<span class="journal-label"> / field notes</span></a><nav aria-label="${locale==='vi'?'Điều hướng':'Navigation'}"><a href="${pathFor(locale)}">${locale==='vi'?'Bài viết':'Journal'}</a><a href="/${locale==='vi'?'vi/':''}docs/">${locale==='vi'?'Tài liệu':'Docs'}</a><button type="button" data-theme-toggle aria-label="${locale==='vi'?'Đổi giao diện sáng tối':'Change color theme'}">◐</button></nav></header>${content}<footer><a href="/">ClarkCant</a><p>${locale==='vi'?'Những ghi chép về cách chúng tôi xây dựng.':'Notes on how we build.'}</p><a href="${pathFor(locale)}feed.xml">RSS</a><a href="/blog/editor">${locale==='vi'?'Biên tập':'Studio'}</a></footer><script type="module" src="${script}"></script></body></html>`;
}
export function renderBlock(block:Block,locale:Locale,article?:Article):string {
  const caption=block.caption?`<figcaption>${escape(block.caption)}</figcaption>`:'';
  const attributes=`id="${escape(block.id)}" class="block block-${block.type}"`;
  switch(block.type) {
    case 'text': return `<div ${attributes}>${block.text.split(/\n\s*\n/).map(p=>`<p>${escape(p).replace(/\n/g,'<br>')}</p>`).join('')}</div>`;
    case 'heading': return `<h${block.level} ${attributes}>${escape(block.text)}</h${block.level}>`;
    case 'layout': return `<section ${attributes} data-layout="${block.layout}">${block.children.map(b=>renderBlock(b,locale,article)).join('')}</section>`;
    case 'image': return `<figure ${attributes}><img src="${escape(block.src)}" alt="${escape(block.alt)}" loading="lazy" decoding="async">${caption}</figure>`;
    case 'carousel': return `<figure ${attributes}><div class="carousel" tabindex="0" aria-label="${locale==='vi'?'Bộ ảnh, cuộn để xem':'Image gallery, scroll to explore'}">${block.images.map(i=>`<img src="${escape(i.src)}" alt="${escape(i.alt)}" loading="lazy">`).join('')}</div><p class="eyebrow">${locale==='vi'?'Cuộn ngang để xem ảnh':'Scroll to explore'}</p>${caption}</figure>`;
    case 'code': return `<figure ${attributes}><div class="code-label">${escape(block.language)}</div><pre tabindex="0"><code>${escape(block.code)}</code></pre>${caption}</figure>`;
    case 'video': return `<figure ${attributes}><video src="${escape(block.src)}" controls preload="none"></video><details><summary>${locale==='vi'?'Nội dung video':'Transcript'}</summary><p>${escape(block.transcript)}</p></details>${caption}</figure>`;
    case 'youtube': return `<figure ${attributes}><iframe title="${escape(block.caption || 'YouTube')}" src="https://www.youtube-nocookie.com/embed/${block.videoId}" loading="lazy" referrerpolicy="no-referrer" allow="fullscreen" sandbox="allow-scripts allow-same-origin allow-presentation"></iframe><details><summary>${locale==='vi'?'Nội dung video':'Transcript'}</summary><p>${escape(block.transcript)}</p></details>${caption}</figure>`;
    case 'sandbox': return `<section ${attributes}><p>${escape(block.explanation)}</p><button type="button" data-run-sandbox>${locale==='vi'?'Chạy ví dụ':'Run experiment'}</button><button type="button" data-stop-sandbox hidden>${locale==='vi'?'Dừng':'Stop'}</button><div data-sandbox-host></div><script type="application/json" data-sandbox>${scriptJson({html:block.html,css:block.css,js:block.js})}</script><details><summary>${locale==='vi'?'Mã nguồn':'Source code'}</summary><pre>${escape(block.html)}</pre><pre>${escape(block.css)}</pre><pre>${escape(block.js)}</pre></details></section>`;
    case 'survey': return `<section ${attributes}><form data-survey data-article="${escape(article?.id ?? '')}" data-locale="${locale}" data-block="${escape(block.id)}"><fieldset><legend>${escape(block.question)}</legend>${block.options.map((o,i)=>`<label class="survey-option"><input type="radio" name="option" value="${i}" required>${escape(o)}</label>`).join('')}</fieldset><button type="submit" ${article?'':'disabled'}>${locale==='vi'?'Gửi phản hồi':'Send response'}</button><p role="status" aria-live="polite"></p></form></section>`;
    case 'widget': return `<figure ${attributes}><div data-widget-host></div><script type="application/json" data-widget>${scriptJson(block)}</script><p>${escape(block.semantic)}</p>${block.rows.length?`<details><summary>${locale==='vi'?'Dữ liệu':'Underlying data'}</summary><pre>${escape(JSON.stringify(block.rows,null,2))}</pre></details>`:''}${caption}</figure>`;
  }
}
export function articlePage(article:Article,locale:Locale,site:string,preview=false) {
  const doc=article.document; const localized=doc[locale]; const canonical=site+pathFor(locale,article.slug); const opposite=locale==='en'?'vi':'en';
  const structured={'@context':'https://schema.org','@type':'BlogPosting',headline:localized.title,description:localized.description,author:{'@type':'Person',name:doc.author},dateModified:article.updated_at,inLanguage:locale,mainEntityOfPage:canonical,...(doc.hero?{image:new URL(doc.hero,site).href}:{})};
  const head=`<meta name="description" content="${escape(localized.description)}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en" href="${site+pathFor('en',article.slug)}"><link rel="alternate" hreflang="vi" href="${site+pathFor('vi',article.slug)}"><link rel="alternate" type="text/markdown" href="${canonical}.md"><meta property="og:type" content="article"><meta property="og:title" content="${escape(localized.title)}"><meta property="og:description" content="${escape(localized.description)}"><meta property="og:url" content="${canonical}">${doc.hero?`<meta property="og:image" content="${escape(new URL(doc.hero,site).href)}">`:''}<meta name="twitter:card" content="summary_large_image">${preview?'<meta name="robots" content="noindex,nofollow">':''}<script type="application/ld+json">${scriptJson(structured)}</script>`;
  const toc=flatten(localized.blocks).filter(b=>b.type==='heading').map(b=>`<a href="#${escape(b.id)}">${escape('text' in b?b.text:'')}</a>`).join('');
  return shell(localized.title,locale,`<main id="main" data-accent="${doc.accent}">${preview?'<div class="preview-banner">Private preview · not published</div>':''}<article class="article"><header class="article-hero"><div class="eyebrow">${doc.tags.map(escape).join(' / ') || 'ClarkCant / Engineering'}</div><h1>${escape(localized.title)}</h1><p class="dek">${escape(localized.description)}</p><div class="byline"><span>${escape(doc.author)}</span><time datetime="${escape(article.updated_at)}">${escape(article.updated_at.slice(0,10))}</time><a href="${preview?`/blog/preview/${article.id}?locale=${opposite}`:pathFor(opposite,article.slug)}" lang="${opposite}">${opposite==='vi'?'Tiếng Việt':'English'}</a></div>${doc.hero?`<img class="hero-image" src="${escape(doc.hero)}" alt="" fetchpriority="high">`:''}</header><div class="reading-tools"><details><summary>${locale==='vi'?'Trong bài viết này':'In this article'}</summary><nav>${toc}</nav></details>${preview?'':`<div class="share-tools"><a href="${canonical}.md">.md</a><button data-copy-markdown data-url="${canonical}.md">Copy Markdown</button><button data-ask-ai="chatgpt" data-url="${canonical}">ChatGPT ↗</button><button data-ask-ai="gemini" data-url="${canonical}">Gemini ↗</button><button data-ask-ai="claude" data-url="${canonical}">Claude ↗</button></div>`}<p role="status" data-share-status></p></div><div class="article-body">${localized.blocks.map(b=>renderBlock(b,locale,preview?undefined:article)).join('')}</div></article></main>`,head);
}
export function indexPage(articles:Awaited<ReturnType<import('./content-service.ts').ContentService['list']>>,locale:Locale,site:string,page=1,hasMore=false) {
  return shell(locale==='vi'?'Ghi chép kỹ thuật':'Field notes',locale,`<main id="main" class="journal"><header class="journal-hero"><p class="eyebrow">ClarkCant / Engineering journal</p><h1>${locale==='vi'?'Ý tưởng.<br>Thử nghiệm.<br><em>Trải nghiệm.</em>':'Ideas.<br>Experiments.<br><em>Experiences.</em>'}</h1><div class="journal-intro"><p>${locale==='vi'?'Khám phá cách ClarkCant được xây dựng. Đọc, thử và tìm hiểu ngay trong từng bài viết.':'Inside the making of ClarkCant. Read the thinking, play with the details, and see how it works.'}</p><a href="${pathFor(locale==='en'?'vi':'en')}">${locale==='en'?'Tiếng Việt':'English'} ↗</a></div></header><section class="article-list" aria-label="${locale==='vi'?'Bài viết':'Articles'}">${articles.length?articles.map((a,i)=>`<a class="article-link" href="${pathFor(locale,a.slug)}"><span class="article-number">${String((page-1)*20+i+1).padStart(2,'0')}</span><div><p class="eyebrow">${a.tags.map(escape).join(' / ')}</p><h2>${escape(a[locale].title)}</h2><p>${escape(a[locale].description)}</p><span class="byline">${escape(a.author)} · ${a.updated_at.slice(0,10)}</span></div><span class="article-arrow" aria-hidden="true">↗</span></a>`).join(''):`<div class="empty-state"><h2>${locale==='vi'?'Bài viết đầu tiên đang được chuẩn bị.':'The first field note is on its way.'}</h2><p>${locale==='vi'?'Bạn có thể khám phá tài liệu kỹ thuật trong lúc chờ.':'Explore the technical documentation while we get it ready.'}</p><a href="/${locale==='vi'?'vi/':''}docs/">${locale==='vi'?'Đọc tài liệu':'Explore the docs'} ↗</a></div>`}</section><nav class="actions" aria-label="Pagination">${page>1?`<a href="?page=${page-1}">${locale==='vi'?'← Mới hơn':'← Newer'}</a>`:''}${hasMore?`<a href="?page=${page+1}">${locale==='vi'?'Cũ hơn →':'Older →'}</a>`:''}</nav></main>`,`<meta name="description" content="${locale==='vi'?'Blog kỹ thuật tương tác của ClarkCant.':'Interactive engineering notes from ClarkCant.'}"><link rel="canonical" href="${site+pathFor(locale)}${page>1?`?page=${page}`:''}"><link rel="alternate" hreflang="en" href="${site+pathFor('en')}${page>1?`?page=${page}`:''}"><link rel="alternate" hreflang="vi" href="${site+pathFor('vi')}${page>1?`?page=${page}`:''}"><link rel="alternate" type="application/rss+xml" href="${pathFor(locale)}feed.xml">`);
}
export function editorPage() {
  return shell('Studio','en',`<main id="main" class="studio"><header class="studio-heading"><div><p class="eyebrow">ClarkCant / Publishing</p><h1>Studio</h1></div><div class="actions"><span id="account"></span><form action="/auth/logout" method="post"><button>Sign out</button></form></div></header><p id="status" role="status" aria-live="polite">Loading your workspace…</p><section id="library"><div class="actions"><button id="new-article" class="primary">New article</button><button id="connections">Connections & team</button></div><div id="articles" class="article-list"></div><button id="more-articles" hidden>Load more</button></section><section id="edit" hidden><div class="editor-toolbar"><button id="back">← Articles</button><label>Language <select id="locale"><option value="en">English</option><option value="vi">Tiếng Việt</option></select></label><button id="save" class="primary">Save draft</button><button id="preview">Preview saved</button><button id="publish">Publish EN + VI</button><button id="history">History</button><button id="unpublish">Unpublish</button></div><div class="editor-meta"><label>Slug<input id="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*"></label><label>Author<input id="author" required></label><label>Tags, comma separated<input id="tags"></label><label>Palette<select id="accent"><option>violet</option><option>ocean</option><option>moss</option><option>ember</option></select></label><label>Cover image URL<input id="hero"></label><label>Upload image/video<input id="media" type="file" accept="image/png,image/jpeg,image/webp,image/gif,video/mp4,video/webm"></label></div><label class="title-field">Title<input id="title"></label><label>Description<textarea id="description" rows="2"></textarea></label><div id="blocks"></div><div class="add-block"><label>Block<select id="block-type"><option>text</option><option>heading</option><option>layout</option><option>image</option><option>carousel</option><option>code</option><option>widget</option><option>video</option><option>youtube</option><option>sandbox</option><option>survey</option></select></label><button id="add-block">Add block</button></div><div class="actions"><button id="copy-translation">Copy layout to other language</button><button id="survey-results">Survey responses</button></div></section><dialog id="panel"><form method="dialog"><button class="close">Close ×</button></form><div id="panel-content"></div></dialog></main>`,`<meta name="robots" content="noindex,nofollow">`,'/assets/blog/editor.js');
}
