// Test-only content. Never used as production seed data.
const blocks = locale => [
 {id:'intro',type:'text',caption:'',text:locale==='en'?'A widget is a view over structured data. This test article exercises the same renderer as ClarkCant without granting access to a personal runtime.':'Widget là một cách hiển thị dữ liệu có cấu trúc. Bài kiểm thử này dùng cùng renderer với ClarkCant, không cấp quyền truy cập runtime cá nhân.'},
 {id:'diagram-heading',type:'heading',caption:'',text:locale==='en'?'One contract, two surfaces':'Một hợp đồng, hai giao diện',level:'2'},
 {id:'architecture',type:'widget',caption:'',definitionId:'canvas.diagram@1',version:'1.0.0',props:{title:locale==='en'?'A shared rendering path':'Đường hiển thị dùng chung',direction:'LR',nodes:[{id:'document',label:'Document'},{id:'renderer',label:'Renderer'},{id:'browser',label:'Browser'}],edges:[{from:'document',to:'renderer'},{from:'renderer',to:'browser'}]},rows:[],state:{},semantic:locale==='en'?'The document provides validated properties. The shared renderer draws them in a browser with local view state.':'Tài liệu cung cấp các thuộc tính đã kiểm tra. Renderer dùng chung hiển thị chúng trong trình duyệt với trạng thái giao diện cục bộ.'},
 {id:'experiment',type:'sandbox',caption:'',explanation:locale==='en'?'Move the slider to change the circle. This experiment stays in an isolated frame.':'Kéo thanh trượt để đổi kích thước hình tròn. Ví dụ chạy trong frame cách ly.',html:'<label>Radius <input id="radius" type="range" min="20" max="100" value="50"></label><div id="circle"></div>',css:'body{font:18px system-ui;background:#f6f5f2;padding:2rem;color:#17171a}#circle{width:100px;height:100px;background:#6b5fa8;border-radius:50%;margin:2rem auto}',js:'document.querySelector("#radius").oninput = e => { const n=Number(e.target.value)*2; Object.assign(document.querySelector("#circle").style,{width:n+"px",height:n+"px"}); };'},
 {id:'poll',type:'survey',caption:'',question:locale==='en'?'Which view helped you understand?':'Cách hiển thị nào giúp bạn hiểu rõ hơn?',options:locale==='en'?['Diagram','Experiment','Both']:['Sơ đồ','Ví dụ tương tác','Cả hai']}
];
export const articleFixture={schemaVersion:1,author:'ClarkCant · browser test fixture',tags:['Engineering','Widgets'],accent:'violet',en:{title:'Small pieces. A richer way to explain.',description:'An interactive test article about structured content, shared widgets and useful autonomy. Test content, not a production publication.',blocks:blocks('en')},vi:{title:'Từng phần nhỏ. Một cách giải thích sâu hơn.',description:'Bài kiểm thử tương tác về nội dung có cấu trúc, widget dùng chung và khả năng tự chủ. Không phải bài xuất bản chính thức.',blocks:blocks('vi')}};
