import { test } from 'node:test';
import assert from 'node:assert/strict';
import { database } from './database.ts';
import { ContentService } from '../src/lib/content-service.ts';
import { documentSchema, markdown, slugSchema } from '../src/lib/document.ts';
import { authenticate, issueToken, oauth } from '../src/lib/auth.ts';
import { api } from '../src/lib/api.ts';
import { articlePage } from '../src/lib/html.ts';
import type { Environment, Principal } from '../src/lib/platform.ts';

const owner:Principal={subject:'github:1',name:'Test editor',role:'owner',scopes:['blog:read','blog:write','blog:publish','blog:admin']};
const editor:Principal={...owner,role:'editor',scopes:['blog:read','blog:write']};
export const document={schemaVersion:1,author:'ClarkCant test suite',tags:['test'],accent:'violet',en:{title:'Test article',description:'Test-only document',blocks:[{id:'paragraph',type:'text',text:'A real SQL publication test.',caption:''},{id:'poll',type:'survey',question:'Pick one',options:['A','B'],caption:''}]},vi:{title:'Bài kiểm thử',description:'Tài liệu chỉ dùng để kiểm thử',blocks:[{id:'paragraph',type:'text',text:'Kiểm tra lưu dữ liệu SQL.',caption:''},{id:'poll',type:'survey',question:'Chọn một',options:['A','B'],caption:''}]}};
function setup(){const db=database();return {db,service:new ContentService(db),env:{DB:db,SITE_URL:'https://blog.test'} as Environment};}
const input=(key=crypto.randomUUID())=>({slug:'test-article',expectedRevision:0,document,key});

test('drafts stay private; publishing exposes a coherent bilingual revision; restoring preserves newer draft',async()=>{
 const {db,service}=setup();try{const saved=await service.save(owner,input());await assert.rejects(service.get(saved.id,true));assert.deepEqual(await service.list(true),[]);await service.publish(owner,saved.id,1,1);assert.equal((await service.get(saved.id,true)).document.vi.title,document.vi.title);await service.save(owner,{...input(),id:saved.id,expectedRevision:1,document:{...document,en:{...document.en,title:'Second draft'}}});assert.equal((await service.get(saved.id,true)).document.en.title,'Test article');await service.publish(owner,saved.id,2,2);await service.publish(owner,saved.id,1,2);assert.equal((await service.get(saved.id,true)).revision,1);assert.equal((await service.get(saved.id)).revision,2);await service.unpublish(owner,saved.id,2);await assert.rejects(service.get(saved.id,true));}finally{db.close();}
});
test('save retries are idempotent, key reuse and stale edits cannot overwrite',async()=>{const {db,service}=setup();try{const i=input();const saved=await service.save(owner,i);assert.deepEqual(await service.save(owner,i),saved);await assert.rejects(service.save(owner,{...i,slug:'other'}),/new idempotency key/);await service.save(owner,{...input(),id:saved.id,expectedRevision:1});await assert.rejects(service.save(owner,{...input(),id:saved.id,expectedRevision:1}),/newer revision/);assert.equal((await service.history(owner,saved.id)).length,2);}finally{db.close();}});
test('scope rejection does not modify published state',async()=>{const {db,service}=setup();try{const saved=await service.save(editor,input());await assert.rejects(service.publish(editor,saved.id,1,1),/blog:publish/);assert.equal((await service.get(saved.id)).published_revision,null);}finally{db.close();}});
test('surveys only accept published options and persist the publication revision',async()=>{const {db,service}=setup();try{const saved=await service.save(owner,input());await assert.rejects(service.survey(saved.id,'en','poll',0,'visitor'));await service.publish(owner,saved.id,1,1);await assert.rejects(service.survey(saved.id,'en','poll',12,'visitor'));await service.survey(saved.id,'vi','poll',1,'visitor');const row=await db.prepare('SELECT revision,answer FROM surveys').first<{revision:number;answer:string}>();assert.equal(row?.revision,1);assert.equal(JSON.parse(row!.answer).locale,'vi');}finally{db.close();}});
test('semantic output and HTML escape authored content; block IDs remain unique',()=>{const doc=documentSchema.parse({...document,en:{...document.en,title:'</script><script>alert(1)</script>'}});const html=articlePage({id:'test',slug:'test',revision:1,published_revision:1,updated_at:'2026-10-04T00:00:00Z',document:doc},'en','https://blog.test');assert.ok(!html.includes('</script><script>alert(1)'));assert.match(markdown(doc,'en','https://blog.test/blog/test','2026-10-04'),/real SQL publication/);assert.throws(()=>documentSchema.parse({...document,en:{...document.en,blocks:[document.en.blocks[0],document.en.blocks[0]]}}),/Duplicate block id/);});
test('disabled membership and reduced role invalidate existing token powers',async()=>{const {db,env}=setup();try{await db.prepare("INSERT INTO members VALUES('github:1','Test','owner',1)").run();const token=await issueToken(env,'github:1',owner.scopes,'api');const req=new Request('https://blog.test/api/blog/me',{headers:{authorization:`Bearer ${token}`}});assert.ok((await authenticate(req,env)).scopes.includes('blog:publish'));await db.prepare("UPDATE members SET role='editor'").run();assert.ok(!(await authenticate(req,env)).scopes.includes('blog:publish'));await db.prepare('UPDATE members SET active=0').run();await assert.rejects(authenticate(req,env));}finally{db.close();}});
test('cookie mutations require same origin; bearer tokens cannot impersonate sessions',async()=>{const {db,env}=setup();try{await db.prepare("INSERT INTO members VALUES('github:1','Test','owner',1)").run();const token=await issueToken(env,'github:1',owner.scopes,'session');await assert.rejects(authenticate(new Request('https://blog.test/api/blog/save_article',{method:'POST',headers:{cookie:`cc_blog_session=${token}`}}),env),/site/);await assert.rejects(authenticate(new Request('https://blog.test/api/blog/me',{headers:{authorization:`Bearer ${token}`}}),env));}finally{db.close();}});
test('OAuth verifies PKCE, resource, redirect and single use; access token has only granted scopes',async()=>{const {db,env}=setup();try{
 await db.prepare("INSERT INTO members VALUES('github:1','Test','owner',1)").run();const session=await issueToken(env,'github:1',owner.scopes,'session');
 const registered=await oauth(new Request('https://blog.test/oauth/register',{method:'POST',body:JSON.stringify({client_name:'Test MCP',redirect_uris:['https://client.test/callback']})}),env);const client=await registered.json() as {client_id:string};
 const verifier='a'.repeat(64);const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));const challenge=Buffer.from(digest).toString('base64url');
 const fields=new URLSearchParams({client_id:client.client_id,redirect_uri:'https://client.test/callback',resource:'https://blog.test/mcp',response_type:'code',code_challenge_method:'S256',code_challenge:challenge,scope:'blog:read',state:'state',decision:'allow'});
 const authorize=await oauth(new Request('https://blog.test/oauth/authorize',{method:'POST',headers:{cookie:`cc_blog_session=${session}`,origin:env.SITE_URL},body:fields}),env);const target=new URL(authorize.headers.get('location')!);assert.equal(target.searchParams.get('state'),'state');
 const tokenFields=new URLSearchParams({grant_type:'authorization_code',code:target.searchParams.get('code')!,client_id:client.client_id,redirect_uri:'https://client.test/callback',resource:'https://blog.test/mcp',code_verifier:'b'.repeat(64)});
 assert.equal((await oauth(new Request('https://blog.test/oauth/token',{method:'POST',body:tokenFields}),env)).status,400);
 tokenFields.set('code_verifier',verifier);const exchanged=await oauth(new Request('https://blog.test/oauth/token',{method:'POST',body:tokenFields}),env);const token=await exchanged.json() as {access_token:string;scope:string};assert.equal(token.scope,'blog:read');assert.equal((await authenticate(new Request('https://blog.test/mcp',{headers:{authorization:`Bearer ${token.access_token}`}}),env)).scopes.length,1);assert.equal((await oauth(new Request('https://blog.test/oauth/token',{method:'POST',body:tokenFields}),env)).status,400);
}finally{db.close();}});
test('REST and MCP use the same content and scope enforcement',async()=>{const {db,env}=setup();try{await db.prepare("INSERT INTO members VALUES('github:1','Test','owner',1)").run();const token=await issueToken(env,'github:1',owner.scopes,'api');const headers={authorization:`Bearer ${token}`,'content-type':'application/json',accept:'application/json, text/event-stream'};
 const saved=await api(new Request('https://blog.test/api/blog/save_article',{method:'POST',headers,body:JSON.stringify(input())}),env);assert.equal(saved.status,200);
 const initialize=await api(new Request('https://blog.test/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'integration-test',version:'1'}}})}),env);assert.equal(initialize.status,200);
 const tool=await api(new Request('https://blog.test/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'list_articles',arguments:{}}})}),env);assert.equal(tool.status,200);const result=await tool.json() as {result:{structuredContent:{data:unknown[]}}};assert.equal(result.result.structuredContent.data.length,1);
 assert.equal((await api(new Request('https://blog.test/blog/test-article.md'),env)).status,404);
}finally{db.close();}});

test('malformed URLs cannot reach publication rendering',()=>{assert.throws(()=>documentSchema.parse({...document,hero:'https://'}),/valid HTTPS/);assert.throws(()=>documentSchema.parse({...document,hero:'https://user:password@example.com/a.png'}),/valid HTTPS/);});

test('editor routes cannot be used as article slugs; unknown pages stay public 404s',async()=>{
 assert.equal(slugSchema.safeParse('editor').success,false);assert.equal(slugSchema.safeParse('preview').success,false);const {db,env}=setup();try{assert.equal((await api(new Request('https://blog.test/unknown'),env)).status,404);assert.equal((await api(new Request('https://blog.test/blog'),env)).status,308);assert.match(await (await api(new Request('https://blog.test/robots.txt'),env)).text(),/sitemap.xml/);}finally{db.close();}
});

test('revoking connections also invalidates outstanding OAuth codes',async()=>{const {db,env}=setup();try{
 await db.prepare("INSERT INTO members VALUES('github:1','Test','owner',1)").run();const session=await issueToken(env,'github:1',owner.scopes,'session');await db.prepare('INSERT INTO oauth_codes VALUES(?,?,?,?,?,?,?,?)').bind('pending','client','https://client.test','challenge','github:1','blog:read','https://blog.test/mcp',Math.floor(Date.now()/1000)+300).run();
 const response=await api(new Request('https://blog.test/api/blog/tokens/revoke',{method:'POST',headers:{origin:env.SITE_URL,cookie:`cc_blog_session=${session}`}}),env);assert.equal(response.status,200);assert.equal(await db.prepare('SELECT * FROM oauth_codes').first(),null);
 }finally{db.close();}});
